version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    advice.detachedHead: "false"
  commands:
        # - make html
    
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
